### PR TITLE
Include both Commons-lang 2.6 and 3.3.2 into Crucible

### PR DESCRIPTION
**Pull request by Irgendwer01**
Fixes Compatibility with the Pack Gregtech: New Horizons in future Versions but not breaks other packs

### CODE REVIEW

**Comment by bartimaeusnek** [comment]
A quick note on this:
Vanilla Minecraft uses 3.3.2, so any mod that is making use of lang3 is not compatible with the current crucible version.

**Comment by evernife** [comment]
I dont think adding a lib to libs folder is the correct way to do this.

And i dont think that "Vanilla Minecraft uses 3.3.2, so any mod that is making use of lang3 is not compatible with the current crucible version."

As we use the same commons-lang:commons-lang as "Thermos, Mohist, UraniumMC"

Can you give me an example of mod that does not work only in CrucibleMC (besides the one you noticed)?

**Comment by Irgendwer01** [comment]
> 
> 
> I dont think adding a lib to libs folder is the correct way to do this.
@evernife That was temporarily because it always used the wrong link till i found the workaround, if needed i can remove the Jar from the libs folder

**Comment by evernife** [comment]
```
String[] testArray = org.apache.commons.lang3.ArrayUtils.add(new String[]{"This", "is", "A"},"Test");
FMLLog.info("[EverForgeLib] " + Arrays.toString(testArray));
FMLLog.info("[EverForgeLib] " + testArray);
```
output: 
> [17:08:05] [Server thread/INFO] [FML/everforgelib]: [EverForgeLib] CustomNPCs listener enabled...
> [17:08:05] [Server thread/INFO] [FML/everforgelib]: [EverForgeLib] [This, is, A, Test]
> [17:08:05] [Server thread/INFO] [FML/everforgelib]: [EverForgeLib] [Ljava.lang.String;@424ef526
            
Are you sure lang3 is not working?
If minecraft uses it, there would be no way to remove it from minecraft :/

**Comment by juanmuscaria** [comment]
I also did some testings, the project already include that dependency
```
[20:51:48] [main/INFO]: [aaaa] [This, is, A, Test]
[20:51:48] [main/INFO]: [bbb] [Ljava.lang.String;@644baf4a
[20:51:48] [main/INFO]: [location] jar:file:/home/juan/Desktop/clean/libraries/net/minecraft/server/1.7.10/server-1.7.10.jar!/org/apache/commons/lang3/ArrayUtils.class
```
So no need to re-add an library that already exist inside minecraft.

**Pull request closed without merging**
