### PR TITLE
[Wiki] Adding ForgeRestrictor

### PR DESCRIPTION
**Pull request by spannerman79**
Works perfectly for restricting access to mod blocks or items that may break protection based pugins - like GriefProtection+

### CODE REVIEW

**Review by Aizistral — CHANGES_REQUESTED** [review]
I would add at least some description of what this mod is and how to use it. I mean, sure, information might be out there, but this is a wiki after all, not merely an archive.

**Comment by spannerman79** [comment]
As there is no `LICENCE.md` in that repo it automatically becomes All Rights Reserved..

Copy/paste anything, even from the `README.md` **without** author consent is a direct breach of copyright.

**Comment by Aizistral** [comment]
I don't see how your remark relates to my suggestion, as I did not suggest to copy-paste existing description. Copyright cannot forbid you to write a couple words of your own describing what the mod does.

**Comment by spannerman79** [comment]
> I don't see how your remark relates to my suggestion, as I did not suggest to copy-paste existing description. Copyright cannot forbid you to write a couple words of your own describing what the mod does.

Actually it does.  What the author states  in the wayback machine link given. is in fact **exactly** what the mod does.

It doesn't matter how many times you attempt to re-word it ( ie plagiarism ) with a limited amount of text that described **exactly** what the mod does actually does become plagiarism, which in turn ir claim for copyright.

**Comment by Aizistral** [comment]
Don't you think it sounds a little... ridiculous? Nobody can copyright that, because it is literally too generic to copyright. If you copy a whole bunch of text as-is - sure, but if you write it yourself - nah. It pretty much goes on the same level as stealing art styles.

**Comment by spannerman79** [comment]
> Don't you think it sounds a little... ridiculous? Nobody can copyright that, because it is literally too generic to copyright. If you copy a whole bunch of text as-is - sure, but if you write it yourself - nah. It pretty much goes on the same level as stealing art styles.

No it isn't.  

But if you _beleive_ that point of view actually suggest changes instead of just tiggering a review **without** suggestions.

**Comment by Aizistral** [comment]
> But if you beleive that point of view actually suggest changes instead of just tiggering a review without suggestions.
I have outlined my suggestion as precisely as it can get. I could write description myself if that's what you want, but I'm not the one suggesting to add this mod to the wiki, so I did expect this is something you can manage on your own.
In the end, it is not that you are not entitled to your opinion and that you cannot follow your personal precautions. Arguments I outlined above are there only to make sure people people will not submit to this fearmongering without doing their own due diligence.

**Comment by spannerman79** [comment]
It seems that you don't understand copyright to "assume" fear mongering.

All I will state on this matter is to do some **actual** research on plagiarism. Some _very_ perfect examples are when Melania Trump took "notes" 🤢 from Michelle Obama.

There are many others for which I won't even bother to attempt to mention as they are litertally endless

>but I'm not the one suggesting to add this mod to the wiki, so I did expect this is something you can manage on your own.

Git etiquette dictates if you trigger a review you **actually** make direct suggestions to code, be to java, cpp, etc or even to a `.md` file. Seeing as you didn't I can only assume you that you "didn't like" the PR but didn't have any constructive edits. Only a comment. Don't attempt to strawman the issue. I can see right thought it.

**Comment by Aizistral** [comment]
WTF, I literally made a direct suggestion?? At this point your logic is just beyond your comprehension.

And, look, there is a fine line between plagiarism and taking inspiration. We could spend hours arguing where exactly it lies, but what I do know is that I, myself, if I wanted, could write the exact description of what the mod does, and there is no way someone would prevail in the case against me, because I literally did not read the readme on the original repository, and hereby could not copy any part of it. If some parts match - it does not mean plagiarism, it simply means that whatever matches is too generic to be copywritten. Well, at least that's how the law is supposed to work.
I am entirely aware that legal poison is a real problem when dealing with intellectual property owned by influential people or big corporations, because in order to fight them in the court you will likely require a financial muscle. Nonetheless, here we are dealing with neither, so taking extreme precautions in this case is both unuseful and impractical.

**Comment by spannerman79** [comment]
> WTF, I literally made a direct suggestion?? At this point your logic is just beyond my comprehension.
> 
> And, look, there is a fine line between plagiarism and taking inspiration. We could spend hours arguing where exactly it lies, but what I do know is that I, myself, if I wanted, could write the exact description of what the mod does, and there is no way someone would prevail in the case against me, because I literally did not read the readme on the original repository, and hereby could not copy any part of it. If some parts match - it does not mean plagiarism, it simply means that whatever matches is too generic to be copywritten. Well, at least that's how the law is supposed to work. I am entirely aware that legal poison is a real problem when dealing with intellectual property owned by influential people or big corporations, because in order to fight them in the court you will likely require a financial muscle. Nonetheless, here we are dealing with neither, so taking extreme precautions in this case is both unuseful and impractical.

Then why don't you.

Bugger it, I'm done with this project.

**Comment by EverNife** [comment]
WTF is this?

**Comment by brunoxkk0** [comment]
All this discussion is really necessary?

**Pull request closed without merging**
