### PR TITLE
Add whitelist for items to bypass spawn protection

### PR DESCRIPTION
**Pull request by tacopeland**
This will let server owners choose which modded items bypass spawn protection, which could be useful for servers with mines in the spawn world to selectively allow modded pickaxes, for example.

### CODE REVIEW

**Comment by evernife** [comment]
The most common cenário is people to disable the default minecraft spawn protection and use other plugins like WorldGuard to handle this.

I personally don't dislike the idea, but, i dont see if this is reallly necessary.

I usually require a more fine "filtering" for my plugins, like having an ID:META whitelist or something like that.

Anyway, if @juanmuscaria or @brunoxkk0 wants to merge this, you will need to fix the double usage of 

`Item.getIdFromItem(ep.getHeldItem().getItem()))`

**Comment by Irgendwer01** [comment]
@tacopeland this is more a job for a plugin, not for the Server Software, use a Protection plugin like Redprotect or Towny. It can and will just cause many issues that will make alot more work for the devs.

**Comment by tacopeland** [comment]
This would be for modded items that bypass worldguard restrictions like Applied Energistics 2's Matter Cannon.

**Comment by evernife** [comment]
> This would be for modded items that bypass worldguard restrictions like Applied Energistics 2's Matter Cannon.

I suggest using a plugin like ForgeRestrictor from KaiKikuchi, he will solve these type of problems.
He has support for WorldGuard and for GriefPreventionPlus.
Its easy to add support for other plugins as well.

Or even create a Mixin to fix the mods themselvs with Grimoire-Mixins.

The point is that this merge will not solve the problem as a whole.

**Comment by tacopeland** [comment]
ForgeRestrictor is dead, this is the least painful fix for this problem.

**Comment by evernife** [comment]
So, if this protection works, it will only take effect on the /spawn

What about player's homes? Warps? Etc?

**Comment by tacopeland** [comment]
This is world-based, not region based. You can specify the protected worlds in Crucible.yml (dev branch) like so:
```yml
  # List of world names where the usage of modded itens and blocks will be disabled for
  protectedWorld:
  - spawn
  - pvparena
  # List of numeric item IDs for modded items that can be used in protected worlds
  protectedWorldWhitelist:
  - 4920
  - 4967
  - 4968
  - 4969
  - ...
```

**Comment by juanmuscaria** [comment]
It was a feature on Thermos already where any world that contains spawn in the name all mod itens are blocked for non opped players, I added a config that replaces it in a way you choose what words have that protection. I'll be merging the pull request, but I might change the per id to <modid:item:meta>. Other more specific protections still should be made using plugins.
Before I merge it, I'll ask you to make a few changes, remove the double usage of `Item.getIdFromItem(ep.getHeldItem().getItem()))` and add a whitelist as blacklist boolean option that inverts the whitelist and uses it as blacklist if possible.

**Comment by tacopeland** [comment]
Changes are pushed.

**Review by juanmuscaria — APPROVED** [review]
Everything seems good, I'll be merging the changes.

**Comment by juanmuscaria** [comment]
Thank you for your contribution.

**Comment by xmssss** [comment]
@juanmuscaria why used item IDs, and not material name's?

**Comment by juanmuscaria** [comment]
Material names are always weird and hard to get, and as far as I know it doesn't support specific item metadata, it also would be better to just use forge's item registry since everyone knows how to get the item registry name so no need for a plugin to get the item material or look through the logs to find it.

**Pull request merged**
