### PR TITLE
Run sync tasks scheduled for the same tick FIFO

### PR DESCRIPTION
**Pull request by fantahund**
https://github.com/CrucibleMC/Crucible/issues/113

### CODE REVIEW

**Comment by EverNife** [comment]
I started to look for this patch.

Are you sure that the "task.getID()" ensure the order?

---------------------------------

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/scheduler/CraftScheduler.java#83

I think on the latestes versions of spigot they store the nanoSecond of creation of the task and compare based on that.

**Comment by Brokkonaut** [comment]
It was changed here: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/4f34a67b5ed70f88ef857d13de1ee3ec433f0ad7 but thats more or less another issue - currently with or without the changes in pr #113 the server would fail when taskids overflow, because negative and possible duplicate taskids are not expected in several places.

**Comment by juanmuscaria** [comment]
Looks good, I'll be merging it to staging once I finish reworking the release cycle.
It may be important to also bring that other spigot patch as well.

**Comment by juanmuscaria** [comment]
Could you retarget this pull request to the staging branch?

**Comment by EverNife** [comment]
> It was changed here: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/4f34a67b5ed70f88ef857d13de1ee3ec433f0ad7 but thats more or less another issue - currently with or without the changes in pr #113 the server would fail when taskids overflow, because negative and possible duplicate taskids are not expected in several places.

I think its better to implement the new system

**Comment by juanmuscaria** [comment]
Manually added at 31a50c6da7e2f3f95e8c3651d3c47e8500570f3a

**Pull request closed without merging**
